const fs = require('fs');
const path = require('path');

const LANG_CONTEXT_PATH = path.resolve(__dirname, '../src/context/LanguageContext.tsx');

const dictionaries = {
  mr: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'एआय-संचालित डिजिटल शेती ऑपरेटिंग सिस्टम',
    'common.logout': 'लॉगआउट',
    'common.login': 'लॉगिन',
    'common.googleLogin': 'गुगल सह लॉगिन करा',
    'common.email': 'ईमेल पत्ता',
    'common.password': 'पासवर्ड',
    'common.submit': 'प्रस्तुत करा',
    'common.cancel': 'रद्द करा',
    'common.save': 'जतन करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.search': 'शोधा...',
    'common.actions': 'कृती',
    'common.status': 'स्थिती',
    'common.loading': 'लोड होत आहे...',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.myFarms': 'माझी शेती',
    'nav.weather': 'हवामान माहिती',
    'nav.disease': 'रोग शोध',
    'nav.aiCopilot': 'एआय कोपायलट',
    'nav.cashbook': 'कॅशबुक',
    'nav.analytics': 'विश्लेषण',
    'nav.community': 'शेतकरी समुदाय',
    'nav.reports': 'अहवाल',
    'nav.profile': 'प्रोफाइल',
    'nav.about': 'आमच्याबद्दल',
    'hero.title': 'शेतकऱ्यांसाठी भारतातील सर्वात हुशार एआय प्लॅटफॉर्म',
    'hero.subtitle': 'एकाच प्लॅटफॉर्मवर अनेक शेतांचे व्यवस्थापन करा, पिकांचे रोग शोधा, हवामानावर लक्ष ठेवा, नफा ट्रॅक करा, एआय शिफारसी मिळवा आणि शेतकऱ्यांशी जोडा.',
    'hero.cta.start': 'स्मार्ट शेती सुरू करा',
    'hero.cta.download': 'अॅप डाउनलोड करा',
    'features.title': 'उत्पादन वाढवण्यासाठी तुम्हाला आवश्यक असलेले सर्व काही',
    'features.subtitle': 'लहान आणि मोठ्या दोन्ही शेतकऱ्यांसाठी बनवलेले आधुनिक कृषी तंत्रज्ञान.',
    'testimonials.title': 'भारतातील प्रगतीशील शेतकऱ्यांचा विश्वास',
    'testimonials.subtitle': 'करीमनगर आणि त्यापलीकडे आधुनिक तंत्रज्ञानाने पिकाचे उत्पादन आणि नफा वाढवण्यास कशी मदत केली ते पहा.',
    'onboard.title': 'चला तुमचे पहिले शेत सेटअप करूया',
    'onboard.step1': 'स्वागत',
    'onboard.step2': 'भाषा निवडा',
    'onboard.step3': 'शेताचा तपशील जोडा',
    'onboard.step4': 'सूचना',
    'onboard.step5': 'तयार',
    'onboard.farmName': 'शेताचे नाव',
    'onboard.farmLocation': 'स्थान (शहर/गाव)',
    'onboard.farmCrop': 'पिकाचा प्रकार',
    'onboard.farmArea': 'शेताचे क्षेत्रफळ (एकर)',
    'onboard.soilType': 'मातीचा प्रकार',
    'onboard.irrigationMethod': 'सिंचन पद्धत',
    'onboard.enableAlerts': 'हवामान सूचना सक्षम करा',
    'onboard.enableDiseaseAlerts': 'रोग प्रादुर्भाव सूचना सक्षम करा',
    'onboard.enableGovAlerts': 'सरकारी योजना सूचना सक्षम करा',
    'onboard.completeTitle': 'तुमचे KisanAI डॅशबोर्ड तयार आहे!',
    'onboard.completeDesc': 'कृषीच्या भविष्यात आपले स्वागत आहे. आता आपण हवामान ट्रॅक करू शकता, कॅश लॉग व्यवस्थापित करू शकता आणि पीक आरोग्यासाठी स्कॅन करू शकता.',
    'onboard.next': 'पुढील पाऊल',
    'onboard.prev': 'मागे',
    'onboard.finish': 'डॅशबोर्डवर जा',
    'dash.welcome': 'पुन्हा स्वागत आहे,',
    'dash.weatherSummary': 'हवामान सारांश',
    'dash.activeAlerts': 'स्मार्ट सूचना',
    'dash.aiRecommendations': 'एआय शिफारस टिकर',
    'dash.recentTransactions': 'अलीकडील खर्च',
    'dash.totalFarms': 'सक्रिय शेती',
    'dash.netProfit': 'निव्वळ नफा',
    'dash.cropDistribution': 'पीक उत्पादनाचा अंदाज',
    'dash.emptyFarms': 'एआय शिफारसी आणि हवामान माहिती मिळवण्यासाठी तुमचे पहिले शेत जोडा.',
    'farm.add': 'नवीन शेत जोडा',
    'farm.coordinates': 'जीपीएस निर्देशक',
    'farm.timeline': 'शेताची टाइमलाइन',
    'farm.soil.clay': 'चिकण माती',
    'farm.soil.sandy': 'वाळूमय माती',
    'farm.soil.loam': 'लोम माती',
    'farm.soil.red': 'तांबडी माती',
    'farm.soil.black': 'काळी कापसाची माती',
    'farm.irrigation.drip': 'ठिबक सिंचन',
    'farm.irrigation.sprinkler': 'तुषार सिंचन',
    'farm.irrigation.flood': 'पूर सिंचन',
    'farm.irrigation.rainfed': 'पावसावर आधारित',
    'farm.drawBoundary': 'शेताची सीमा आखा',
    'farm.boundarySaved': 'सीमा निर्देशक शेताच्या प्रोफाइलशी यशस्वीरित्या जोडले गेले आहेत.',
    'weather.title': 'शेती हवामान माहिती',
    'weather.forecast': '७ दिवसांचा अंदाज',
    'weather.rainProb': 'पावसाची शक्यता',
    'weather.windSpeed': 'वाऱ्याचा वेग',
    'weather.humidity': 'आद्रता',
    'weather.temp': 'तापमान',
    'weather.uv': 'यूव्ही इंडेक्स',
    'weather.alert.heavyRain': '६ तासांत मुसळधार पावसाची शक्यता. खत देणे पुढे ढकला.',
    'weather.alert.wind': 'उद्या वेगवान वारे (>२५ किमी/तास) वाहण्याची शक्यता. आधार संरचना सुरक्षित करा.',
    'weather.alert.humidity': 'जास्त आद्रतेमुळे बुरशीजन्य रोगांचा धोका वाढू शकतो. बारकाईने लक्ष ठेवा.',
    'disease.title': 'एआय रोग निदान',
    'disease.upload': 'पिकाचा फोटो अपलोड करा',
    'disease.dragDrop': 'पानाचा फोटो अपलोड करण्यासाठी ड्रॅग आणि ड्रॉप करा किंवा क्लिक करा',
    'disease.scanning': 'एआय पिकाच्या उतींचे विश्लेषण करत आहे...',
    'disease.detected': 'रोग आढळला',
    'disease.confidence': 'विश्वासार्हता स्कोअर',
    'disease.prevention': 'प्रतिबंधात्मक उपाय',
    'disease.treatment': 'उपचार योजना',
    'disease.fertilizer': 'पोषकद्रव्ये समायोजन',
    'disease.askAi': 'एआय कोपायलटला विचारा',
    'disease.askCommunity': 'समुदायाला विचारा',
    'copilot.title': 'एआय फार्म कोपायलट',
    'copilot.subtitle': 'तुमच्या पसंतीच्या भाषेत कोणताही कृषी प्रश्न विचारा.',
    'copilot.placeholder': 'एआयला विचारा: "मी कोणते पीक घ्यावे?" किंवा "कापसासाठी सर्वोत्तम खत कोणते?"...',
    'copilot.voiceInput': 'बोलण्यासाठी दाबून ठेवा',
    'copilot.voiceSpeaking': 'ऐकत आहे...',
    'copilot.voiceOutput': 'मोठ्याने वाचा',
    'cash.title': 'फार्म कॅशबुक लेजर',
    'cash.addIncome': 'उत्पन्न जोडा',
    'cash.addExpense': 'खर्च जोडा',
    'cash.income': 'उत्पन्न',
    'cash.expense': 'खर्च',
    'cash.category': 'वर्गवारी',
    'cash.amount': 'रक्कम (₹)',
    'cash.date': 'तारीख',
    'cash.description': 'टीप / वर्णन',
    'cash.net': 'निव्वळ बचत',
    'cash.breakdown': 'खर्च वर्गवारीचे वर्गीकरण',
    'cash.insights': 'आर्थिक एआय अंतर्दृष्टी',
    'cash.empty': 'नफा समजून घेण्यासाठी खर्चाचा मागोवा घ्या.',
    'cash.farmProfitability': 'शेतनिहाय नफा वर्गीकरण',
    'cash.farmName': 'शेताचे नाव',
    'cash.crop': 'पीक',
    'cash.netProfit': 'निव्वळ नफा',
    'cash.unassigned': 'अवर्गीकृत',
    'comm.title': 'शेतकरी समुदाय नेटवर्क',
    'comm.feed': 'चर्चा फीड',
    'comm.groups': 'शेती गट',
    'comm.experts': 'तज्ञ पडताळणी',
    'comm.createPost': 'अपडेट सामायिक करा किंवा प्रश्न विचारा...',
    'comm.postBtn': 'पोस्ट प्रकाशित करा',
    'comm.nearby': 'जवळपासचे शेतकरी',
    'comm.repScore': 'समुदाय प्रतिष्ठा',
    'comm.badge': 'बॅज पातळी',
    'comm.follow': 'फॉलो करा',
    'comm.message': 'संदेश'
  },
  ta: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'AI-ஆற்றல் கொண்ட டிஜிட்டல் விவசாய இயக்க முறைமை',
    'common.logout': 'வெளியேறு',
    'common.login': 'உள்நுழை',
    'common.googleLogin': 'கூகுள் மூலம் உள்நுழையவும்',
    'common.email': 'மின்னஞ்சல் முகவரி',
    'common.password': 'கடவுச்சொல்',
    'common.submit': 'சமர்ப்பி',
    'common.cancel': 'ரத்துசெய்',
    'common.save': 'சேமி',
    'common.delete': 'அழி',
    'common.edit': 'தொகு',
    'common.search': 'தேடு...',
    'common.actions': 'செயல்கள்',
    'common.status': 'நிலை',
    'common.loading': 'ஏற்றப்படுகிறது...',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.myFarms': 'எனது பண்ணைகள்',
    'nav.weather': 'வானிலை தகவல்',
    'nav.disease': 'நோய் கண்டறிதல்',
    'nav.aiCopilot': 'AI உதவியாளர்',
    'nav.cashbook': 'பணப்புத்தகம்',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.community': 'விவசாயி சமூகம்',
    'nav.reports': 'அறிக்கைகள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.about': 'எங்களைப் பற்றி',
    'hero.title': 'விவசாயிகளுக்கான இந்தியாவின் அதிநவீன AI தளம்',
    'hero.subtitle': 'ஒரே தளத்தில் பல பண்ணைகளை நிர்வகிக்கவும், பயிர் நோய்களைக் கண்டறியவும், வானிலையைக் கண்காணிக்கவும், லாபத்தைக் கண்காணிக்கவும், AI பரிந்துரைகளைப் பெறவும் மற்றும் விவசாயிகளுடன் இணையவும்.',
    'hero.cta.start': 'புத்திசாலித்தனமாக விவசாயத்தைத் தொடங்குங்கள்',
    'hero.cta.download': 'செயலியைப் பதிவிறக்குக',
    'features.title': 'மகசூலை அதிகரிக்க தேவையான அனைத்தும்',
    'features.subtitle': 'சிறு மற்றும் பெரு விவசாயிகள் இருவருக்குமாக உருவாக்கப்பட்ட நவீன விவசாயத் தொழில்நுட்பம்.',
    'testimonials.title': 'இந்தியாவின் முற்போக்கு விவசாயிகளால் நம்பப்படுகிறது',
    'testimonials.subtitle': 'கரிம்நகர் மற்றும் அதற்கு அப்பால் பயிர் மகசூல் மற்றும் லாபத்தை அதிகரிக்க நவீன தொழில்நுட்பம் எவ்வாறு உதவியது என்று பாருங்கள்.',
    'onboard.title': 'உங்கள் முதல் பண்ணையை அமைப்போம்',
    'onboard.step1': 'வரவேற்பு',
    'onboard.step2': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'onboard.step3': 'பண்ணை விவரங்களைச் சேர்க்கவும்',
    'onboard.step4': 'அறிவிப்புகள்',
    'onboard.step5': 'தயார்',
    'onboard.farmName': 'பண்ணையின் பெயர்',
    'onboard.farmLocation': 'இருப்பிடம் (நகரம்/கிராமம்)',
    'onboard.farmCrop': 'பயிர் வகை',
    'onboard.farmArea': 'பண்ணை பரப்பு (ஏக்கர்)',
    'onboard.soilType': 'மண் வகை',
    'onboard.irrigationMethod': 'பாசன முறை',
    'onboard.enableAlerts': 'வானிலை எச்சரிக்கைகளை இயக்கு',
    'onboard.enableDiseaseAlerts': 'நோய் பாதிப்பு எச்சரிக்கைகளை இயக்கு',
    'onboard.enableGovAlerts': 'அரசு திட்ட எச்சரிக்கைகளை இயக்கு',
    'onboard.completeTitle': 'உங்கள் KisanAI டாஷ்போர்டு தயாராக உள்ளது!',
    'onboard.completeDesc': 'விவசாயத்தின் எதிர்காலத்திற்கு உங்களை வரவேற்கிறோம். இப்போது நீங்கள் வானிலையைக் கண்காணிக்கலாம், பணப் பதிவுகளை நிர்வகிக்கலாம் மற்றும் பயிர் ஆரோக்கியத்தை ஸ்கேன் செய்யலாம்.',
    'onboard.next': 'அடுத்த படி',
    'onboard.prev': 'பின்னால்',
    'onboard.finish': 'டாஷ்போர்டுக்குச் செல்லவும்',
    'dash.welcome': 'மீண்டும் வருக,',
    'dash.weatherSummary': 'வானிலை சுருக்கம்',
    'dash.activeAlerts': 'புத்திசாலி எச்சரிக்கைகள்',
    'dash.aiRecommendations': 'AI பரிந்துரை டிக்கர்',
    'dash.recentTransactions': 'சமீபத்திய செலவுகள்',
    'dash.totalFarms': 'செயலில் உள்ள பண்ணைகள்',
    'dash.netProfit': 'நிகர லாபம்',
    'dash.cropDistribution': 'பயிர் மகசூல் கணிப்புகள்',
    'dash.emptyFarms': 'AI பரிந்துரைகள் மற்றும் வானிலை தகவல்களைப் பெற உங்கள் முதல் பண்ணையைச் சேர்க்கவும்.',
    'farm.add': 'புதிய பண்ணையைச் சேர்',
    'farm.coordinates': 'ஜிபிஎஸ் ஒருங்கிணைப்புகள்',
    'farm.timeline': 'பண்ணை காலவரிசை',
    'farm.soil.clay': 'களிமண்',
    'farm.soil.sandy': 'மணல் மண்',
    'farm.soil.loam': 'வண்டல் மண்',
    'farm.soil.red': 'செம்மண்',
    'farm.soil.black': 'கரிசல் மண்',
    'farm.irrigation.drip': 'சொட்டு நீர் பாசனம்',
    'farm.irrigation.sprinkler': 'தெளிப்பான் பாசனம்',
    'farm.irrigation.flood': 'வாய்மடைப் பாசனம்',
    'farm.irrigation.rainfed': 'மானாவாரி (மழை தங்கிய)',
    'farm.drawBoundary': 'பண்ணை எல்லையை வரையவும்',
    'farm.boundarySaved': 'எல்லை ஒருங்கிணைப்புகள் பண்ணை சுயவிவரத்துடன் வெற்றிகரமாக இணைக்கப்பட்டுள்ளன.',
    'weather.title': 'பண்ணை வானிலை தகவல்',
    'weather.forecast': '7-நாள் முன்கணிப்பு',
    'weather.rainProb': 'மழைக்கான வாய்ப்பு',
    'weather.windSpeed': 'காற்றின் வேகம்',
    'weather.humidity': 'ஈரப்பதம்',
    'weather.temp': 'வெப்பநிலை',
    'weather.uv': 'புற ஊதா குறியீடு (UV)',
    'weather.alert.heavyRain': '6 மணி நேரத்திற்குள் பலத்த மழை எதிர்பார்க்கப்படுகிறது. உரம் போடுவதைத் தள்ளிப்போடுங்கள்.',
    'weather.alert.wind': 'நாளை பலத்த காற்று (>25 கிமீ/மணி) எதிர்பார்க்கப்படுகிறது. பயிர் பாதுகாப்பு அமைப்புகள் பாதுகாப்பாக இருப்பதை உறுதி செய்யவும்.',
    'weather.alert.humidity': 'அதிக ஈரப்பதம் பூஞ்சை நோய் அபாயத்தை அதிகரிக்கலாம். உன்னிப்பாகக் கண்காணிக்கவும்.',
    'disease.title': 'AI நோய் கண்டறிதல்',
    'disease.upload': 'பயிர் புகைப்படத்தைப் பதிவேற்றவும்',
    'disease.dragDrop': 'இலை புகைப்படத்தைப் பதிவேற்ற இழுத்து விடவும் அல்லது கிளிக் செய்யவும்',
    'disease.scanning': 'AI பயிர் திசுக்களை பகுப்பாய்வு செய்கிறது...',
    'disease.detected': 'கண்டறியப்பட்ட நோய்',
    'disease.confidence': 'நம்பிக்கை மதிப்பெண்',
    'disease.prevention': 'தடுப்பு நடவடிக்கைகள்',
    'disease.treatment': 'சிகிச்சை திட்டம்',
    'disease.fertilizer': 'ஊட்டச்சத்து சரிசெய்தல்',
    'disease.askAi': 'AI உதவியாளரிடம் கேளுங்கள்',
    'disease.askCommunity': 'சமூகத்திடம் கேளுங்கள்',
    'copilot.title': 'AI பண்ணை உதவியாளர்',
    'copilot.subtitle': 'உங்களுக்கு விருப்பமான மொழியில் எந்தவொரு விவசாய கேள்வியையும் கேளுங்கள்.',
    'copilot.placeholder': 'AI-யிடம் கேளுங்கள்: "நான் எந்த பயிரை வளர்க்க வேண்டும்?" அல்லது "பருத்திக்கு சிறந்த உரம் எது?"...',
    'copilot.voiceInput': 'பேசுவதற்கு அழுத்திப் பிடிக்கவும்',
    'copilot.voiceSpeaking': 'கேட்டுக்கொண்டிருக்கிறது...',
    'copilot.voiceOutput': 'உரக்க வாசி',
    'cash.title': 'பண்ணை பணப்புத்தக பேரேடு',
    'cash.addIncome': 'வருவாயைச் சேர்',
    'cash.addExpense': 'செலவைச் சேர்',
    'cash.income': 'வருவாய்',
    'cash.expense': 'செலவு',
    'cash.category': 'வகை',
    'cash.amount': 'தொகை (₹)',
    'cash.date': 'தேதி',
    'cash.description': 'குறிப்புகள் / விளக்கம்',
    'cash.net': 'நிகர சேமிப்பு',
    'cash.breakdown': 'செலவு வகைகளின் பகுப்பாய்வு',
    'cash.insights': 'நிதிசார் AI நுண்ணறிவு',
    'cash.empty': 'லாபத்தைப் புரிந்துகொள்ள செலவுகளைக் கண்காணிக்கவும்.',
    'cash.farmProfitability': 'பண்ணை வாரியான லாப பகுப்பாய்வு',
    'cash.farmName': 'பண்ணையின் பெயர்',
    'cash.crop': 'பயிர்',
    'cash.netProfit': 'நிகர லாபம்',
    'cash.unassigned': 'ஒதுக்கப்படாதது',
    'comm.title': 'விவசாயி சமூக நெட்வொர்க்',
    'comm.feed': 'விவாத ஊட்டம்',
    'comm.groups': 'விவசாயக் குழுக்கள்',
    'comm.experts': 'சரிபார்க்கப்பட்ட நிபுணர்கள்',
    'comm.createPost': 'ஒரு செய்தியைப் பகிரவும் அல்லது கேள்வி கேட்கவும்...',
    'comm.postBtn': 'பதிவை வெளியிடு',
    'comm.nearby': 'அருகிலுள்ள விவசாயிகள்',
    'comm.repScore': 'சமூக நற்பெயர்',
    'comm.badge': 'பதக்க நிலை',
    'comm.follow': 'தொடரவும்',
    'comm.message': 'செய்தி'
  },
  kn: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'AI-ಚಾಲಿತ ಡಿಜಿಟಲ್ ಕೃಷಿ ಕಾರ್ಯಾಚರಣಾ ವ್ಯವಸ್ಥೆ',
    'common.logout': 'ಲಾಗ್ಔಟ್',
    'common.login': 'ಲಾಗಿನ್',
    'common.googleLogin': 'ಗೂಗಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'common.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'common.password': 'ಪಾಸ್ವರ್ಡ್',
    'common.submit': 'ಸಲ್ಲಿಸು',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸು',
    'common.save': 'ಉಳಿಸು',
    'common.delete': 'ಅಳಿಸು',
    'common.edit': 'ಸಂಪಾದಿಸು',
    'common.search': 'ಹುಡುಕಿ...',
    'common.actions': 'ಕ್ರಮಗಳು',
    'common.status': 'ಸ್ಥಿತಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'nav.dashboard': 'ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    'nav.myFarms': 'ನನ್ನ ಜಮೀನುಗಳು',
    'nav.weather': 'ಹವಾಮಾನ ಮಾಹಿತಿ',
    'nav.disease': 'ರೋಗ ಪತ್ತೆ ಹಚ್ಚುವಿಕೆ',
    'nav.aiCopilot': 'AI ಸಹಾಯಕ',
    'nav.cashbook': 'ಕ್ಯಾಶ್ಬುಕ್',
    'nav.analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'nav.community': 'ರೈತ ಸಮುದಾಯ',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'hero.title': 'ರೈತರಿಗಾಗಿ ಭಾರತದ ಅತ್ಯಂತ ಸ್ಮಾರ್ಟ್ AI ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
    'hero.subtitle': 'ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ ಅನೇಕ ಜಮೀನುಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ಬೆಳೆ ರೋಗಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ, ಹವಾಮಾನವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ, ಲಾಭವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, AI ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ ಮತ್ತು ರೈತರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ.',
    'hero.cta.start': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪ್ರಾರಂಭಿಸಿ',
    'hero.cta.download': 'ಅಪ್ಲಿಕೇಶನ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'features.title': 'ಇಳುವರಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ',
    'features.subtitle': 'ಸಣ್ಣ ಮತ್ತು ದೊಡ್ಡ ರೈತರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾದ ಆಧುನಿಕ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ.',
    'testimonials.title': 'ಭಾರತದ ಪ್ರಗತಿಪರ ರೈತರ ನಂಬಿಕೆ',
    'testimonials.subtitle': 'ಕರೀಂನಗರ ಮತ್ತು ಸುತ್ತಮುತ್ತಲಿನ ಪ್ರದೇಶಗಳಲ್ಲಿ ಬೆಳೆ ಇಳುವರಿ ಮತ್ತು ಲಾಭವನ್ನು ಹೆಚ್ಚಿಸಲು ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಿದೆ ಎಂದು ನೋಡಿ.',
    'onboard.title': 'ನಿಮ್ಮ ಮೊದಲ ಜಮೀನನ್ನು ಹೊಂದಿಸೋಣ',
    'onboard.step1': 'ಸ್ವಾಗತ',
    'onboard.step2': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    'onboard.step3': 'ಜಮೀನಿನ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ',
    'onboard.step4': 'ಅಧಿಸೂಚನೆಗಳು',
    'onboard.step5': 'ಸಿದ್ಧ',
    'onboard.farmName': 'ಜಮೀನಿನ ಹೆಸರು',
    'onboard.farmLocation': 'ಸ್ಥಳ (ನಗರ/ಗ್ರಾಮ)',
    'onboard.farmCrop': 'ಬೆಳೆ ಪ್ರಕಾರ',
    'onboard.farmArea': 'ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)',
    'onboard.soilType': 'ಮಣ್ಣಿನ ಪ್ರಕಾರ',
    'onboard.irrigationMethod': 'ನೀರಾವರಿ ವಿಧಾನ',
    'onboard.enableAlerts': 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'onboard.enableDiseaseAlerts': 'ರೋಗ ಹರಡುವಿಕೆಯ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'onboard.enableGovAlerts': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'onboard.completeTitle': 'ನಿಮ್ಮ KisanAI ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸಿದ್ಧವಾಗಿದೆ!',
    'onboard.completeDesc': 'ಕೃಷಿಯ ಭವಿಷ್ಯಕ್ಕೆ ನಿಮಗೆ ಸ್ವಾಗತ. ಈಗ ನೀವು ಹವಾಮಾನವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಬಹುದು, ನಗದು ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಬಹುದು ಮತ್ತು ಬೆಳೆಗಳ ಆರೋಗ್ಯವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಬಹುದು.',
    'onboard.next': 'ಮುಂದಿನ ಹಂತ',
    'onboard.prev': 'ಹಿಂದಕ್ಕೆ',
    'onboard.finish': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    'dash.welcome': 'ಮರಳಿ ಸ್ವಾಗತ,',
    'dash.weatherSummary': 'ಹವಾಮಾನ ಸಾರಾಂಶ',
    'dash.activeAlerts': 'ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆಗಳು',
    'dash.aiRecommendations': 'AI ಶಿಫಾರಸು ಟಿಕ್ಕರ್',
    'dash.recentTransactions': 'ಇತ್ತೀಚಿನ ವೆಚ್ಚಗಳು',
    'dash.totalFarms': 'ಸಕ್ರಿಯ ಜಮೀನುಗಳು',
    'dash.netProfit': 'ನಿವ್ವಳ ಲಾಭ',
    'dash.cropDistribution': 'ಬೆಳೆ ಇಳುವರಿ ಮುನ್ಸೂಚನೆಗಳು',
    'dash.emptyFarms': 'AI ಶಿಫಾರಸುಗಳು ಮತ್ತು ಹವಾಮಾನ ಮಾಹಿತಿಯನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಮೊದಲ ಜಮೀನನ್ನು ಸೇರಿಸಿ.',
    'farm.add': 'ಹೊಸ ಜಮೀನು ಸೇರಿಸಿ',
    'farm.coordinates': 'ಜಿಪಿಎಸ್ ಕೋಆರ್ಡಿನೇಟ್ಸ್',
    'farm.timeline': 'ಜಮೀನಿನ ಟೈಮ್ಲೈನ್',
    'farm.soil.clay': 'ಜೇಡಿ ಮಣ್ಣು',
    'farm.soil.sandy': 'ಮರಳು ಮಣ್ಣು',
    'farm.soil.loam': 'ರೊಂಪ ಮಣ್ಣು (ಲೋಮ್)',
    'farm.soil.red': 'ಕೆಂಪು ಮಣ್ಣು',
    'farm.soil.black': 'ಕಪ್ಪು ಹತ್ತಿ ಮಣ್ಣು',
    'farm.irrigation.drip': 'ಹನಿ ನೀರಾವರಿ',
    'farm.irrigation.sprinkler': 'ಸ್ಪ್ರಿಂಕ್ಲರ್ ನೀರಾವರಿ',
    'farm.irrigation.flood': 'ಹರಿ ನೀರಾವರಿ (ಫ್ಲಡ್)',
    'farm.irrigation.rainfed': 'ಮಳೆ ಆಶ್ರಿತ',
    'farm.drawBoundary': 'ಜಮೀನಿನ ಗಡಿಯನ್ನು ಎಳೆಯಿರಿ',
    'farm.boundarySaved': 'ಗಡಿಯ ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಜಮೀನಿನ ಪ್ರೊಫೈಲ್‌ಗೆ ಯಶಸ್ವಿಯಾಗಿ ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ.',
    'weather.title': 'ಜಮೀನಿನ ಹವಾಮಾನ ಮಾಹಿತಿ',
    'weather.forecast': '7-ದಿನಗಳ ಮುನ್ಸೂಚನೆ',
    'weather.rainProb': 'ಮಳೆಯ ಸಾಧ್ಯತೆ',
    'weather.windSpeed': 'ಗಾಳಿಯ ವೇಗ',
    'weather.humidity': 'ಆರ್ದ್ರತೆ',
    'weather.temp': 'ತಾಪಮಾನ',
    'weather.uv': 'ಯುವಿ ಇಂಡೆಕ್ಸ್',
    'weather.alert.heavyRain': '6 ಗಂಟೆಗಳ ಒಳಗೆ ಭಾರಿ ಮಳೆಯ ನಿರೀಕ್ಷೆಯಿದೆ. ಗೊಬ್ಬರ ಹಾಕುವುದನ್ನು ಮುಂದೂಡಿ.',
    'weather.alert.wind': 'ನಾಳೆ ಬಲವಾದ ಗಾಳಿ (>25 ಕಿಮೀ/ಗಂಟೆ) ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ. ಬೆಳೆ ರಕ್ಷಣೆ ರಚನೆಗಳನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಿ.',
    'weather.alert.humidity': 'ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆಯು ಶಿಲೀಂಧ್ರ ರೋಗಗಳ ಅಪಾಯವನ್ನು ಹೆಚ್ಚಿಸಬಹುದು. ಸೂಕ್ಷ್ಮವಾಗಿ ಗಮನಿಸಿ.',
    'disease.title': 'AI ರೋಗ ಪತ್ತೆ ಹಚ್ಚುವಿಕೆ',
    'disease.upload': 'ಬೆಳೆಯ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'disease.dragDrop': 'ಎಲೆಯ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಲು ಎಳೆದು ಹಾಕಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ',
    'disease.scanning': 'AI ಬೆಳೆಯ ಅಂಗಾಂಶಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    'disease.detected': 'ಪತ್ತೆಯಾದ ರೋಗ',
    'disease.confidence': 'ನಂಬಿಕೆಯ ಸ್ಕೋರ್',
    'disease.prevention': 'ತಡೆಗಟ್ಟುವ ಕ್ರಮಗಳು',
    'disease.treatment': 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
    'disease.fertilizer': 'ಪೋಷಕಾಂಶಗಳ ಹೊಂದಾಣಿಕೆ',
    'disease.askAi': 'AI ಸಹಾಯಕನನ್ನು ಕೇಳಿ',
    'disease.askCommunity': 'ಸಮುದಾಯವನ್ನು ಕೇಳಿ',
    'copilot.title': 'AI ಜಮೀನಿನ ಸಹಾಯಕ',
    'copilot.subtitle': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಯಾವುದೇ ಕೃಷಿ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ.',
    'copilot.placeholder': 'AI ಗೆ ಕೇಳಿ: "ನಾನು ಯಾವ ಬೆಳೆಯನ್ನು ಬೆಳೆಯಬೇಕು?" ಅಥವಾ "ಹತ್ತಿಗೆ ಉತ್ತಮ ಗೊಬ್ಬರ ಯಾವುದು?"...',
    'copilot.voiceInput': 'ಮಾತನಾಡಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    'copilot.voiceSpeaking': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...',
    'copilot.voiceOutput': 'ಗಟ್ಟಿಯಾಗಿ ಓದಿ',
    'cash.title': 'ಜಮೀನಿನ ನಗದು ಪುಸ್ತಕ ಲೆಡ್ಜರ್',
    'cash.addIncome': 'ಆದಾಯ ಸೇರಿಸಿ',
    'cash.addExpense': 'ವೆಚ್ಚ ಸೇರಿಸಿ',
    'cash.income': 'ಆದಾಯ',
    'cash.expense': 'ವೆಚ್ಚ',
    'cash.category': 'ವರ್ಗ',
    'cash.amount': 'ಮೊತ್ತ (₹)',
    'cash.date': 'ದಿನಾಂಕ',
    'cash.description': 'ಟಿಪ್ಪಣಿಗಳು / ವಿವರಣೆ',
    'cash.net': 'ನಿವ್ವಳ ಉಳಿತಾಯ',
    'cash.breakdown': 'ವೆಚ್ಚಗಳ ವರ್ಗೀಕರಣ',
    'cash.insights': 'ಹಣಕಾಸು AI ಒಳನೋಟಗಳು',
    'cash.empty': 'ಲಾಭದಾಯಕತೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ವೆಚ್ಚಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    'cash.farmProfitability': 'ಜಮೀನು-ವಾರು ಲಾಭದಾಯಕತೆಯ ವಿಶ್ಲೇಷಣೆ',
    'cash.farmName': 'ಜಮೀನಿನ ಹೆಸರು',
    'cash.crop': 'ಬೆಳೆ',
    'cash.netProfit': 'ನಿವ್ವಳ ಲಾಭ',
    'cash.unassigned': 'ನಿಯೋಜಿಸದ',
    'comm.title': 'ರೈತ ಸಮುದಾಯ ನೆಟ್‌ವರ್ಕ್',
    'comm.feed': 'ಚರ್ಚಾ ಫೀಡ್',
    'comm.groups': 'ಕೃಷಿ ಗುಂಪುಗಳು',
    'comm.experts': 'ಪರಿಣಿತರನ್ನು ಪರಿಶೀಲಿಸಿ',
    'comm.createPost': 'ಅಪ್‌ಡೇಟ್ ಹಂಚಿಕೊಳ್ಳಿ ಅಥವಾ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    'comm.postBtn': 'ಪೋಸ್ಟ್ ಪ್ರಕಟಿಸಿ',
    'comm.nearby': 'ಹತ್ತಿರದ ರೈತರು',
    'comm.repScore': 'ಸಮುದಾಯದ ಖ್ಯಾತಿ',
    'comm.badge': 'ಬ್ಯಾಡ್ಜ್ ಮಟ್ಟ',
    'comm.follow': 'ಫಾಲೋ ಮಾಡಿ',
    'comm.message': 'ಸಂದೇಶ'
  },
  bn: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'AI-চালিত ডিজিটাল কৃষি অপারেটিং সিস্টেম',
    'common.logout': 'লগআউট',
    'common.login': 'লগইন',
    'common.googleLogin': 'Google দিয়ে সাইন ইন করুন',
    'common.email': 'ইমেল ঠিকানা',
    'common.password': 'পাসওয়ার্ড',
    'common.submit': 'জমা দিন',
    'common.cancel': 'বাতিল করুন',
    'common.save': 'সংরক্ষণ করুন',
    'common.delete': 'মুছে ফেলুন',
    'common.edit': 'সম্পাদনা করুন',
    'common.search': 'খুঁজুন...',
    'common.actions': 'পদক্ষেপ',
    'common.status': 'অবস্থা',
    'common.loading': 'লোড হচ্ছে...',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.myFarms': 'আমার খামার',
    'nav.weather': 'আবহাওয়ার তথ্য',
    'nav.disease': 'রোগ সনাক্তকরণ',
    'nav.aiCopilot': 'AI সহকারী',
    'nav.cashbook': 'ক্যাশ বুক',
    'nav.analytics': 'বিশ্লেষণ',
    'nav.community': 'কৃষক সম্প্রদায়',
    'nav.reports': 'রিপোর্ট',
    'nav.profile': 'প্রোফাইল',
    'nav.about': 'আমাদের সম্পর্কে',
    'hero.title': 'কৃষকদের জন্য ভারতের সবচেয়ে স্মার্ট AI প্ল্যাটফর্ম',
    'hero.subtitle': 'একটি একক প্ল্যাটফর্মে একাধিক খামার পরিচালনা করুন, ফসলের রোগ সনাক্ত করুন, আবহাওয়া পর্যবেক্ষণ করুন, লাভ ট্র্যাক করুন, AI সুপারিশ পান এবং কৃষকদের সাথে যুক্ত হন।',
    'hero.cta.start': 'স্মার্ট চাষ শুরু করুন',
    'hero.cta.download': 'অ্যাপ ডাউনলোড করুন',
    'features.title': 'ফলন বাড়ানোর জন্য আপনার প্রয়োজনীয় সবকিছু',
    'features.subtitle': 'ক্ষুদ্র ও বৃহৎ উভয় কৃষকদের জন্য নির্মিত আধুনিক কৃষি প্রযুক্তি।',
    'testimonials.title': 'ভারতের প্রগতিশীল কৃষকদের দ্বারা বিশ্বস্ত',
    'testimonials.subtitle': 'করিমনগর এবং তার বাইরে কীভাবে আধুনিক প্রযুক্তি ফসলের ফলন এবং লাভ বাড়াতে সাহায্য করেছে তা দেখুন।',
    'onboard.title': 'আসুন আপনার প্রথম খামার সেটআপ করি',
    'onboard.step1': 'স্বাগতম',
    'onboard.step2': 'ভাষা নির্বাচন করুন',
    'onboard.step3': 'খামারের বিবরণ যোগ করুন',
    'onboard.step4': 'বিজ্ঞপ্তি',
    'onboard.step5': 'প্রস্তুত',
    'onboard.farmName': 'খামারের নাম',
    'onboard.farmLocation': 'অবস্থান (শহর/গ্রাম)',
    'onboard.farmCrop': 'ফসলের ধরন',
    'onboard.farmArea': 'খামারের ক্ষেত্রফল (একর)',
    'onboard.soilType': 'মাটির ধরন',
    'onboard.irrigationMethod': 'সেচ পদ্ধতি',
    'onboard.enableAlerts': 'আবহাওয়া সতর্কতা সক্রিয় করুন',
    'onboard.enableDiseaseAlerts': 'রোগের প্রাদুর্ভাব সতর্কতা সক্রিয় করুন',
    'onboard.enableGovAlerts': 'সরকারি প্রকল্প সতর্কতা সক্রিয় করুন',
    'onboard.completeTitle': 'আপনার KisanAI ড্যাশবোর্ড প্রস্তুত!',
    'onboard.completeDesc': 'কৃষির ভবিষ্যতে আপনাকে স্বাগতম। এখন আপনি আবহাওয়া ট্র্যাক করতে পারেন, নগদ লগ পরিচালনা করতে পারেন এবং ফসলের রোগ স্ক্যান করতে পারেন।',
    'onboard.next': 'পরবর্তী পদক্ষেপ',
    'onboard.prev': 'পিছনে',
    'onboard.finish': 'ড্যাশবোর্ডে যান',
    'dash.welcome': 'স্বাগতম,',
    'dash.weatherSummary': 'আবহাওয়ার সংক্ষিপ্তসার',
    'dash.activeAlerts': 'স্মার্ট সতর্কতা',
    'dash.aiRecommendations': 'AI সুপারিশ টিকার',
    'dash.recentTransactions': 'সাম্প্রতিক খরচ',
    'dash.totalFarms': 'সক্রিয় খামার',
    'dash.netProfit': 'নিট লাভ',
    'dash.cropDistribution': 'ফসলের ফলন পূর্বাভাস',
    'dash.emptyFarms': 'AI সুপারিশ এবং আবহাওয়ার তথ্য পেতে আপনার প্রথম খামার যোগ করুন।',
    'farm.add': 'নতুন খামার যোগ করুন',
    'farm.coordinates': 'জিপিএস স্থানাঙ্ক',
    'farm.timeline': 'খামার সময়রেখা',
    'farm.soil.clay': 'এঁটেল মাটি',
    'farm.soil.sandy': 'বেলে মাটি',
    'farm.soil.loam': 'দোআঁশ মাটি',
    'farm.soil.red': 'লাল মাটি',
    'farm.soil.black': 'কালো কার্পাস মাটি',
    'farm.irrigation.drip': 'ড্রিপ সেচ',
    'farm.irrigation.sprinkler': 'ঝরনা সেচ (স্প্রিঙ্কলার)',
    'farm.irrigation.flood': 'প্লাবন সেচ (ফ্লাড)',
    'farm.irrigation.rainfed': 'বৃষ্টি নির্ভর',
    'farm.drawBoundary': 'খামারের সীমানা আঁকুন',
    'farm.boundarySaved': 'সীমানার স্থানাঙ্ক খামার প্রোফাইলের সাথে সফলভাবে যুক্ত করা হয়েছে।',
    'weather.title': 'খামারের আবহাওয়ার তথ্য',
    'weather.forecast': '৭ দিনের পূর্বাভাস',
    'weather.rainProb': 'বৃষ্টির সম্ভাবনা',
    'weather.windSpeed': 'বাতাসের গতি',
    'weather.humidity': 'আর্দ্রতা',
    'weather.temp': 'তাপমাত্রা',
    'weather.uv': 'ইউভি সূচক',
    'weather.alert.heavyRain': '৬ ঘণ্টার মধ্যে ভারী বৃষ্টির সম্ভাবনা। সার প্রয়োগ স্থগিত রাখুন।',
    'weather.alert.wind': 'আগামীকাল তীব্র বাতাস (>২৫ কিমি/ঘণ্টা) হতে পারে। গাছপালার সহায়ক কাঠামো নিরাপদ করুন।',
    'weather.alert.humidity': 'উচ্চ আর্দ্রতার কারণে ছত্রাকজনিত রোগের ঝুঁকি বাড়তে পারে। সতর্ক থাকুন।',
    'disease.title': 'AI রোগ নির্ণয়',
    'disease.upload': 'ফসলের ছবি আপলোড করুন',
    'disease.dragDrop': 'পাতার ছবি আপলোড করতে ড্র্যাগ ও ড্রপ করুন অথবা ক্লিক করুন',
    'disease.scanning': 'AI ফসলের টিস্যু বিশ্লেষণ করছে...',
    'disease.detected': 'রোগ সনাক্ত হয়েছে',
    'disease.confidence': 'নির্ভরযোগ্যতার হার',
    'disease.prevention': 'প্রতিরোধমূলক ব্যবস্থা',
    'disease.treatment': 'চিকিৎসা পরিকল্পনা',
    'disease.fertilizer': 'পুষ্টি সমন্বয়',
    'disease.askAi': 'AI সহকারীকে জিজ্ঞাসা করুন',
    'disease.askCommunity': 'সম্প্রদায়কে জিজ্ঞাসা করুন',
    'copilot.title': 'AI খামার সহকারী',
    'copilot.subtitle': 'আপনার পছন্দের ভাষায় যেকোনো কৃষি সংক্রান্ত প্রশ্ন জিজ্ঞাসা করুন।',
    'copilot.placeholder': 'AI-কে জিজ্ঞাসা করুন: "আমার কোন ফসল চাষ করা উচিত?" বা "তুলার জন্য সেরা সার কোনটি?"...',
    'copilot.voiceInput': 'বলার জন্য টিপে ধরে রাখুন',
    'copilot.voiceSpeaking': 'শুনছে...',
    'copilot.voiceOutput': 'জোরে পড়ুন',
    'cash.title': 'খামার ক্যাশ বুক খতিয়ান',
    'cash.addIncome': 'আয় যোগ করুন',
    'cash.addExpense': 'খরচ যোগ করুন',
    'cash.income': 'আয়',
    'cash.expense': 'ব্যয়',
    'cash.category': 'বিভাগ',
    'cash.amount': 'পরিমাণ (₹)',
    'cash.date': 'তারিখ',
    'cash.description': 'নোট / বিবরণ',
    'cash.net': 'নিট সঞ্চয়',
    'cash.breakdown': 'ব্যয় বিভাগের বিবরণ',
    'cash.insights': 'আর্থিক AI অন্তর্দৃষ্টি',
    'cash.empty': 'লাভজনকতা বুঝতে খরচ ট্র্যাক করুন।',
    'cash.farmProfitability': 'খামার-ভিত্তিক লাভজনকতার বিবরণ',
    'cash.farmName': 'খামারের নাম',
    'cash.crop': 'ফসল',
    'cash.netProfit': 'নিট লাভ',
    'cash.unassigned': 'অনির্ধারিত',
    'comm.title': 'কৃষক সামাজিক নেটওয়ার্ক',
    'comm.feed': 'আলোচনা ফিড',
    'comm.groups': 'কৃষি গোষ্ঠী',
    'comm.experts': 'যাচাইকৃত বিশেষজ্ঞ',
    'comm.createPost': 'নতুন আপডেট শেয়ার করুন বা প্রশ্ন জিজ্ঞাসা করুন...',
    'comm.postBtn': 'পোস্ট প্রকাশ করুন',
    'comm.nearby': 'নিকটবর্তী কৃষক',
    'comm.repScore': 'সম্প্রদায়ের সুনাম',
    'comm.badge': 'ব্যাজ স্তর',
    'comm.follow': 'ফলো করুন',
    'comm.message': 'বার্তা পাঠান'
  },
  pa: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'AI-ਸੰਚਾਲਿਤ ਡਿਜੀਟਲ ਖੇਤੀਬਾੜੀ ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ',
    'common.logout': 'ਲੌਗਆਊਟ',
    'common.login': 'ਲੌਗਇਨ',
    'common.googleLogin': 'Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    'common.email': 'ਈਮੇਲ ਪਤਾ',
    'common.password': 'ਪਾਸਵਰਡ',
    'common.submit': 'ਸਪੁਰਦ ਕਰੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.save': 'ਸੰਭਾਲੋ',
    'common.delete': 'ਮਿਟਾਓ',
    'common.edit': 'ਸੋਧੋ',
    'common.search': 'ਖੋਜੋ...',
    'common.actions': 'ਕਾਰਵਾਈਆਂ',
    'common.status': 'ਸਥਿਤੀ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.myFarms': 'ਮੇਰੇ ਖੇਤ',
    'nav.weather': 'ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ',
    'nav.disease': 'ਬੀਮਾਰੀ ਦੀ ਪਛਾਣ',
    'nav.aiCopilot': 'AI ਸਹਾਇਕ',
    'nav.cashbook': 'ਕੈਸ਼ਬੁੱਕ',
    'nav.analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'nav.community': 'ਕਿਸਾਨ ਭਾਈਚਾਰਾ',
    'nav.reports': 'ਰਿਪੋਰਟਾਂ',
    'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'nav.about': 'ਸਾਡੇ ਬਾਰੇ',
    'hero.title': 'ਕਿਸਾਨਾਂ ਲਈ ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਸਮਾਰਟ AI ਪਲੇਟਫਾਰਮ',
    'hero.subtitle': 'ਇੱਕੋ ਪਲੇਟਫਾਰਮ \'ਤੇ ਕਈ ਖੇਤਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ, ਫਸਲਾਂ ਦੀਆਂ ਬੀਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਓ, ਮੌਸਮ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ, ਮੁਨਾਫਾ ਟ੍ਰੈਕ ਕਰੋ, AI ਸਿਫ਼ਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਹੋਰ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ।',
    'hero.cta.start': 'ਸਮਾਰਟ ਖੇਤੀ ਸ਼ੁਰੂ ਕਰੋ',
    'hero.cta.download': 'ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ',
    'features.title': 'ਝਾੜ ਵਧਾਉਣ ਲਈ ਲੋੜੀਂਦੀ ਹਰ ਚੀਜ਼',
    'features.subtitle': 'ਛੋਟੇ ਅਤੇ ਵੱਡੇ ਦੋਵਾਂ ਕਿਸਾਨਾਂ ਲਈ ਬਣਾਈ ਗਈ ਆਧੁਨਿਕ ਖੇਤੀਬਾੜੀ ਤਕਨਾਲੋਜੀ।',
    'testimonials.title': 'ਭਾਰਤ ਦੇ ਅਗਾਂਹਵਧੂ ਕਿਸਾਨਾਂ ਦਾ ਭਰੋਸਾ',
    'testimonials.subtitle': 'ਦੇਖੋ ਕਿਵੇਂ ਆਧੁਨਿਕ ਤਕਨੀਕ ਨੇ ਕਰੀਮਨਗਰ ਅਤੇ ਇਸ ਤੋਂ ਬਾਹਰ ਫਸਲਾਂ ਦੇ ਝਾੜ ਅਤੇ ਮੁਨਾਫੇ ਨੂੰ ਵਧਾਉਣ ਵਿੱਚ ਮਦਦ ਕੀਤੀ ਹੈ।',
    'onboard.title': 'ਆਓ ਆਪਣਾ ਪਹਿਲਾ ਖੇਤ ਸੈੱਟਅੱਪ ਕਰੀਏ',
    'onboard.step1': 'ਸੁਆਗਤ ਹੈ',
    'onboard.step2': 'ਭਾਸ਼ਾ ਚੁਣੋ',
    'onboard.step3': 'ਖੇਤ ਦਾ ਵੇਰਵਾ ਜੋੜੋ',
    'onboard.step4': 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
    'onboard.step5': 'ਤਿਆਰ',
    'onboard.farmName': 'ਖੇਤ ਦਾ ਨਾਮ',
    'onboard.farmLocation': 'ਸਥਾਨ (ਸ਼ਹਿਰ/ਪਿੰਡ)',
    'onboard.farmCrop': 'ਫਸਲ ਦੀ ਕਿਸਮ',
    'onboard.farmArea': 'ਖੇਤ ਦਾ ਰਕਬਾ (ਏਕੜ)',
    'onboard.soilType': 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    'onboard.irrigationMethod': 'ਸਿੰਚਾਈ ਵਿਧੀ',
    'onboard.enableAlerts': 'ਮੌਸਮ ਦੇ ਅਲਰਟ ਚਾਲੂ ਕਰੋ',
    'onboard.enableDiseaseAlerts': 'ਬੀਮਾਰੀ ਫੈਲਣ ਦੇ ਅਲਰਟ ਚਾਲੂ ਕਰੋ',
    'onboard.enableGovAlerts': 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦੇ ਅਲਰਟ ਚਾਲੂ ਕਰੋ',
    'onboard.completeTitle': 'ਤੁਹਾਡਾ KisanAI ਡੈਸ਼ਬੋਰਡ ਤਿਆਰ ਹੈ!',
    'onboard.completeDesc': 'ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਹੁਣ ਤੁਸੀਂ ਮੌਸਮ ਨੂੰ ਟ੍ਰੈਕ ਕਰ ਸਕਦੇ ਹੋ, ਖਰਚਿਆਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰ ਸਕਦੇ ਹੋ ਅਤੇ ਫਸਲਾਂ ਦੀ ਬੀਮਾਰੀ ਦੀ ਜਾਂਚ ਕਰ ਸਕਦੇ ਹੋ।',
    'onboard.next': 'ਅਗਲਾ ਕਦਮ',
    'onboard.prev': 'ਪਿੱਛੇ',
    'onboard.finish': 'ਡੈਸ਼ਬੋਰਡ \'ਤੇ ਜਾਓ',
    'dash.welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ,',
    'dash.weatherSummary': 'ਮੌਸਮ ਦਾ ਸਾਰ',
    'dash.activeAlerts': 'ਸਮਾਰਟ ਅਲਰਟ',
    'dash.aiRecommendations': 'AI ਸਿਫ਼ਾਰਸ਼ਾਂ ਦਾ ਫੀਡ',
    'dash.recentTransactions': 'ਹਾਲੀਆ ਖਰਚੇ',
    'dash.totalFarms': 'ਸਰਗਰਮ ਖੇਤ',
    'dash.netProfit': 'ਸ਼ੁੱਧ ਮੁਨਾਫਾ',
    'dash.cropDistribution': 'ਫਸਲ ਦੇ ਝਾੜ ਦਾ ਪੂਰਵਅਨੁਮਾਨ',
    'dash.emptyFarms': 'AI ਸਿਫ਼ਾਰਸ਼ਾਂ ਅਤੇ ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ।',
    'farm.add': 'ਨਵਾਂ ਖੇਤ ਜੋੜੋ',
    'farm.coordinates': 'ਜੀਪੀਐਸ ਨਿਰਦੇਸ਼ਾਂਕ',
    'farm.timeline': 'ਖੇਤ ਦੀ ਟਾਈਮਲਾਈਨ',
    'farm.soil.clay': 'ਚਿਕਣੀ ਮਿੱਟੀ',
    'farm.soil.sandy': 'ਰੇਤਲੀ ਮਿੱਟੀ',
    'farm.soil.loam': 'ਮੈਰਾ ਮਿੱਟੀ (ਲੋਮ)',
    'farm.soil.red': 'ਲਾਲ ਮਿੱਟੀ',
    'farm.soil.black': 'ਕਾਲੀ ਕਪਾਹ ਮਿੱਟੀ',
    'farm.irrigation.drip': 'ਤੁਪਕਾ ਸਿੰਚਾਈ (ਡਰਿੱਪ)',
    'farm.irrigation.sprinkler': 'ਫੁਹਾਰਾ ਸਿੰਚਾਈ',
    'farm.irrigation.flood': 'ਭਰਵਾਂ ਪਾਣੀ ਸਿੰਚਾਈ (ਫਲੱਡ)',
    'farm.irrigation.rainfed': 'ਬਰਸਾਤੀ (ਕੁਦਰਤੀ)',
    'farm.drawBoundary': 'ਖੇਤ ਦੀ ਸੀਮਾ ਰੇਖਾਂਕਿਤ ਕਰੋ',
    'farm.boundarySaved': 'ਖੇਤ ਦੀ ਸੀਮਾ ਨੂੰ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਸਫਲਤਾਪੂਰਵਕ ਲਿੰਕ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    'weather.title': 'ਖੇਤ ਦੇ ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ',
    'weather.forecast': '7-ਦਿਨਾਂ ਦਾ ਪੂਰਵਅਨੁਮਾਨ',
    'weather.rainProb': 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ',
    'weather.windSpeed': 'ਹਵਾ ਦੀ ਰਫ਼ਤਾਰ',
    'weather.humidity': 'ਨਮੀ',
    'weather.temp': 'ਤਾਪਮਾਨ',
    'weather.uv': 'ਯੂਵੀ ਇੰਡੈਕਸ',
    'weather.alert.heavyRain': '6 ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਭਾਰੀ ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ ਹੈ। ਖਾਦ ਪਾਉਣ ਵਿੱਚ ਦੇਰੀ ਕਰੋ।',
    'weather.alert.wind': 'ਕੱਲ੍ਹ ਤੇਜ਼ ਹਵਾਵਾਂ (>25 ਕਿਲੋਮੀਟਰ/ਘੰਟਾ) ਚੱਲਣ ਦੀ ਉਮੀਦ ਹੈ। ਫਸਲਾਂ ਨੂੰ ਸਹਾਰਾ ਦੇਣਾ ਯਕੀਨੀ ਬਣਾਓ।',
    'weather.alert.humidity': 'ਉੱਚ ਨਮੀ ਕਾਰਨ ਉੱਲੀ ਰੋਗਾਂ ਦਾ ਖਤਰਾ ਵੱਧ ਸਕਦਾ ਹੈ। ਨੇੜਿਓਂ ਨਿਗਰਾਨੀ ਕਰੋ।',
    'disease.title': 'AI ਫਸਲ ਰੋਗ ਨਿਦਾਨ',
    'disease.upload': 'ਫਸਲ ਦੀ ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ',
    'disease.dragDrop': 'ਪੱਤੇ ਦੀ ਤਸਵੀਰ ਖਿੱਚ ਕੇ ਇੱਥੇ ਲਿਆਓ ਜਾਂ ਅਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    'disease.scanning': 'AI ਫਸਲ ਦੇ ਟਿਸ਼ੂਆਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...',
    'disease.detected': 'ਪਛਾਣਿਆ ਗਿਆ ਰੋਗ',
    'disease.confidence': 'ਸਟੀਕਤਾ ਦਰ',
    'disease.prevention': 'ਬਚਾਅ ਦੇ ਉਪਾਅ',
    'disease.treatment': 'ਇਲਾਜ ਦੀ ਯੋਜਨਾ',
    'disease.fertilizer': 'ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਵਿਵਸਥਾ',
    'disease.askAi': 'AI ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
    'disease.askCommunity': 'ਭਾਈਚਾਰੇ ਨੂੰ ਪੁੱਛੋ',
    'copilot.title': 'AI ਖੇਤ ਸਹਾਇਕ',
    'copilot.subtitle': 'ਆਪਣੀ ਪਸੰਦ ਦੀ ਭਾਸ਼ਾ ਵਿੱਚ ਕੋਈ ਵੀ ਖੇਤੀਬਾੜੀ ਸੰਬੰਧੀ ਸਵਾਲ ਪੁੱਛੋ।',
    'copilot.placeholder': 'AI ਨੂੰ ਪੁੱਛੋ: "ਮੈਨੂੰ ਕਿਹੜੀ ਫਸਲ ਉਗਾਉਣੀ ਚਾਹੀਦੀ ਹੈ?" ਜਾਂ "ਨਰਮੇ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਖਾਦ ਕਿਹੜੀ ਹੈ?"...',
    'copilot.voiceInput': 'ਬੋਲਣ ਲਈ ਦਬਾ ਕੇ ਰੱਖੋ',
    'copilot.voiceSpeaking': 'ਸੁਣ ਰਿਹਾ ਹੈ...',
    'copilot.voiceOutput': 'ਉੱਚੀ ਪੜ੍ਹੋ',
    'cash.title': 'ਖੇਤ ਬਹੀਖਾਤਾ ਕੈਸ਼ਬੁੱਕ',
    'cash.addIncome': 'ਆਮਦਨ ਜੋੜੋ',
    'cash.addExpense': 'ਖਰਚਾ ਜੋੜੋ',
    'cash.income': 'ਆਮਦਨ',
    'cash.expense': 'ਖਰਚਾ',
    'cash.category': 'ਸ਼੍ਰੇਣੀ',
    'cash.amount': 'ਰਕਮ (₹)',
    'cash.date': 'ਮਿਤੀ',
    'cash.description': 'ਨੋਟਸ / ਵੇਰਵਾ',
    'cash.net': 'ਸ਼ੁੱਧ ਬਚਤ',
    'cash.breakdown': 'ਖਰਚਿਆਂ ਦਾ ਵਰਗੀਕਰਨ',
    'cash.insights': 'ਵਿੱਤੀ AI ਸੂਝ-ਬੂਝ',
    'cash.empty': 'ਮੁਨਾਫੇ ਨੂੰ ਸਮਝਣ ਲਈ ਆਪਣੇ ਖਰਚਿਆਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ।',
    'cash.farmProfitability': 'ਖੇਤ-ਵਾਰ ਮੁਨਾਫੇ ਦਾ ਵੇਰਵਾ',
    'cash.farmName': 'ਖੇਤ ਦਾ ਨਾਮ',
    'cash.crop': 'ਫਸਲ',
    'cash.netProfit': 'ਸ਼ੁੱਧ ਮੁਨਾਫਾ',
    'cash.unassigned': 'ਅਣ-ਨਿਰਧਾਰਤ',
    'comm.title': 'ਕਿਸਾਨ ਸਮਾਜਿਕ ਮੰਚ',
    'comm.feed': 'ਚਰਚਾ ਫੀਡ',
    'comm.groups': 'ਖੇਤੀਬਾੜੀ ਸਮੂਹ',
    'comm.experts': 'ਪ੍ਰਮਾਣਿਤ ਮਾਹਿਰ',
    'comm.createPost': 'ਕੋਈ ਨਵੀਂ ਜਾਣਕਾਰੀ ਸਾਂਝੀ ਕਰੋ ਜਾਂ ਸਵਾਲ ਪੁੱਛੋ...',
    'comm.postBtn': 'ਪੋਸਟ ਕਰੋ',
    'comm.nearby': 'ਨੇੜਲੇ ਕਿਸਾਨ',
    'comm.repScore': 'ਭਾਈਚਾਰਕ ਸਾਖ',
    'comm.badge': 'ਬੈਜ ਦਾ ਪੱਧਰ',
    'comm.follow': 'ਫਾਲੋ ਕਰੋ',
    'comm.message': 'ਸੁਨੇਹਾ ਭੇਜੋ'
  },
  ml: {
    'brand.name': 'KisanAI',
    'brand.tagline': 'AI-അധിഷ്ഠിത ഡിജിറ്റൽ കാർഷിക ഓപ്പറേറ്റിംഗ് സിസ്റ്റം',
    'common.logout': 'ലോഗ്ഔട്ട്',
    'common.login': 'ലോഗിൻ',
    'common.googleLogin': 'Google ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    'common.email': 'ഇമെയിൽ വിലാസം',
    'common.password': 'പാസ്‌വേഡ്',
    'common.submit': 'സമർപ്പിക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സംരക്ഷിക്കുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.edit': 'തിരുത്തുക',
    'common.search': 'തിരയുക...',
    'common.actions': 'നടപടികൾ',
    'common.status': 'നില',
    'common.loading': 'അപ്‌ലോഡ് ചെയ്യുന്നു...',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.myFarms': 'എന്റെ കൃഷിയിടങ്ങൾ',
    'nav.weather': 'കാലാവസ്ഥാ വിവരങ്ങൾ',
    'nav.disease': 'രോഗനിർണ്ണയം',
    'nav.aiCopilot': 'AI സഹായി',
    'nav.cashbook': 'ക്യാഷ്ബുക്ക്',
    'nav.analytics': 'വിശകലനം',
    'nav.community': 'കർഷക കൂട്ടായ്മ',
    'nav.reports': 'റിപ്പോർട്ടുകൾ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.about': 'ഞങ്ങളെക്കുറിച്ച്',
    'hero.title': 'കർഷകർക്കായുള്ള ഇന്ത്യയിലെ ഏറ്റവും മികച്ച AI പ്ലാറ്റ്‌ഫോം',
    'hero.subtitle': 'ഒരു പ്ലാറ്റ്‌ഫോമിൽ ഒന്നിലധികം കൃഷിയിടങ്ങൾ നിയന്ത്രിക്കുക, വിള രോഗങ്ങൾ കണ്ടെത്തുക, കാലാവസ്ഥ നിരീക്ഷിക്കുക, ലാഭം ട്രാക്ക് ചെയ്യുക, AI ശുപാർശകൾ സ്വീകരിക്കുക, മറ്റ് കർഷകരുമായി ബന്ധപ്പെടുക.',
    'hero.cta.start': 'സ്മാർട്ടായി കൃഷി ആരംഭിക്കുക',
    'hero.cta.download': 'ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
    'features.title': 'വിളവ് വർദ്ധിപ്പിക്കാൻ ആവശ്യമായതെല്ലാം',
    'features.subtitle': 'ചെറുകിട-വൻകിട കർഷകർക്കായി പ്രത്യേകം രൂപകൽപ്പന ചെയ്ത ആധുനിക കാർഷിക സാങ്കേതികവിദ്യ.',
    'testimonials.title': 'ഇന്ത്യയിലെ പുരോഗമന കർഷകരുടെ വിശ്വസ്ത പങ്കാളി',
    'testimonials.subtitle': 'കരീംനഗറിലും പരിസര പ്രദേശങ്ങളിലും വിളവ് വർദ്ധിപ്പിക്കാനും ലാഭം കൂട്ടാനും ആധുനിക സാങ്കേതികവിദ്യ എങ്ങനെ സഹായിച്ചുവെന്ന് കാണുക.',
    'onboard.title': 'നിങ്ങളുടെ ആദ്യ കൃഷിയിടം സജ്ജമാക്കാം',
    'onboard.step1': 'സ്വാഗതം',
    'onboard.step2': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'onboard.step3': 'കൃഷിയിട വിവരങ്ങൾ ചേർക്കുക',
    'onboard.step4': 'അറിയിപ്പുകൾ',
    'onboard.step5': 'തയ്യാർ',
    'onboard.farmName': 'കൃഷിയിടത്തിന്റെ പേര്',
    'onboard.farmLocation': 'സ്ഥലം (നഗരം/ഗ്രാമം)',
    'onboard.farmCrop': 'വിളയുടെ ഇനം',
    'onboard.farmArea': 'വിസ്തീർണ്ണം (ഏക്കറിൽ)',
    'onboard.soilType': 'മണ്ണിന്റെ ഇനം',
    'onboard.irrigationMethod': 'നനയ്ക്കൽ രീതി',
    'onboard.enableAlerts': 'കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ സജീവമാക്കുക',
    'onboard.enableDiseaseAlerts': 'രോഗബാധ മുന്നറിയിപ്പുകൾ സജീവമാക്കുക',
    'onboard.enableGovAlerts': 'സർക്കാർ പദ്ധതി അറിയിപ്പുകൾ സജീവമാക്കുക',
    'onboard.completeTitle': 'നിങ്ങളുടെ KisanAI ഡാഷ്‌ബോർഡ് തയ്യാറാണ്!',
    'onboard.completeDesc': 'കൃഷിയുടെ ഭാവിയിലേക്ക് സ്വാഗതം. ഇനി നിങ്ങൾക്ക് കാലാവസ്ഥ ട്രാക്ക് ചെയ്യാം, ഇടപാടുകൾ നിയന്ത്രിക്കാം, വിളകളുടെ ആരോഗ്യം പരിശോധിക്കാം.',
    'onboard.next': 'അടുത്ത പടി',
    'onboard.prev': 'പിന്നിലേക്ക്',
    'onboard.finish': 'ഡാഷ്‌ബോർഡിലേക്ക് പോകുക',
    'dash.welcome': 'വീണ്ടും സ്വാഗതം,',
    'dash.weatherSummary': 'കാലാവസ്ഥാ സംഗ്രഹം',
    'dash.activeAlerts': 'സ്മാർട്ട് അറിയിപ്പുകൾ',
    'dash.aiRecommendations': 'AI ശുപാർശകൾ',
    'dash.recentTransactions': 'സമീപകാല ചെലവുകൾ',
    'dash.totalFarms': 'സജീവ കൃഷിയിടങ്ങൾ',
    'dash.netProfit': 'അറ്റാദായം',
    'dash.cropDistribution': 'വിളവ് പ്രവചനം',
    'dash.emptyFarms': 'AI ശുപാർശകളും കാലാവസ്ഥാ വിവരങ്ങളും ലഭിക്കുന്നതിന് നിങ്ങളുടെ ആദ്യ കൃഷിയിടം ചേർക്കുക.',
    'farm.add': 'പുതിയ കൃഷിയിടം ചേർക്കുക',
    'farm.coordinates': 'ജിപിഎസ് കോർഡിനേറ്റുകൾ',
    'farm.timeline': 'കൃഷി സമയരേഖ',
    'farm.soil.clay': 'കരിമണ്ണ് (കളിമണ്ണ്)',
    'farm.soil.sandy': 'മണൽമണ്ണ്',
    'farm.soil.loam': 'പശിമരാശി മണ്ണ് (ലോം)',
    'farm.soil.red': 'ചെമ്മണ്ണ്',
    'farm.soil.black': 'കറുത്ത പരുത്തി മണ്ണ്',
    'farm.irrigation.drip': 'തുള്ളിനന',
    'farm.irrigation.sprinkler': 'സ്പ്രിംക്ലർ രീതി',
    'farm.irrigation.flood': 'തടം നനയ്ക്കൽ (ഫ്ലഡ്)',
    'farm.irrigation.rainfed': 'മഴയെ ആശ്രയിച്ചുള്ളത്',
    'farm.drawBoundary': 'അതിർത്തി രേഖപ്പെടുത്തുക',
    'farm.boundarySaved': 'കൃഷിയിടത്തിന്റെ അതിർത്തി വിജയകരമായി രേഖപ്പെടുത്തിയിരിക്കുന്നു.',
    'weather.title': 'കാലാവസ്ഥാ വിവരങ്ങൾ',
    'weather.forecast': '7 ദിവസത്തെ പ്രവചനം',
    'weather.rainProb': 'മഴയ്ക്കുള്ള സാധ്യത',
    'weather.windSpeed': 'കാറ്റിന്റെ വേഗത',
    'weather.humidity': 'ആർദ്രത',
    'weather.temp': 'താപനില',
    'weather.uv': 'യുവി ഇൻഡക്സ്',
    'weather.alert.heavyRain': '6 മണിക്കൂറിനുള്ളിൽ ശക്തമായ മഴയ്ക്ക് സാധ്യത. വളപ്രയോഗം മാറ്റിവെക്കുക.',
    'weather.alert.wind': 'നാളെ ശക്തമായ കാറ്റിന് (>25 km/h) സാധ്യത. വിളകൾക്ക് താങ്ങ് നൽകുക.',
    'weather.alert.humidity': 'ഉയർന്ന ആർദ്രത പൂപ്പൽ രോഗങ്ങൾക്ക് കാരണമായേക്കാം. ശ്രദ്ധിക്കുക.',
    'disease.title': 'AI രോഗനിർണ്ണയം',
    'disease.upload': 'വിളയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'disease.dragDrop': 'ഇലയുടെ ചിത്രം ഇവിടെ ഡ്രാഗ് ചെയ്യുക അല്ലെങ്കിൽ ക്ലിක් ചെയ്ത് അപ്‌ലോഡ് ചെയ്യുക',
    'disease.scanning': 'AI ഇലയുടെ കോശങ്ങൾ പരിശോധിക്കുന്നു...',
    'disease.detected': 'കണ്ടെത്തിയ രോഗം',
    'disease.confidence': 'കൃത്യതാനിരക്ക്',
    'disease.prevention': 'പ്രതിരോധ മാർഗ്ഗങ്ങൾ',
    'disease.treatment': 'ചികിത്സാ രീതി',
    'disease.fertilizer': 'വളപ്രയോഗ ക്രമീകരണങ്ങൾ',
    'disease.askAi': 'AI സഹായിയോട് ചോദിക്കുക',
    'disease.askCommunity': 'കൂട്ടായ്മയോട് ചോദിക്കുക',
    'copilot.title': 'AI കാർഷിക സഹായി',
    'copilot.subtitle': 'ഏത് കാർഷിക സംശയങ്ങളും നിങ്ങളുടെ ഇഷ്ടഭാഷയിൽ ചോദിക്കുക.',
    'copilot.placeholder': 'AIയോട് ചോദിക്കുക: "ഞാൻ ഏത് വിളയാണ് നടേണ്ടത്?" അല്ലെങ്കിൽ "പരുത്തിക്ക് ഏറ്റവും അനുയോജ്യമായ വളം ഏതാണ്?"...',
    'copilot.voiceInput': 'സംസാരിക്കാൻ അമർത്തിപ്പിടിക്കുക',
    'copilot.voiceSpeaking': 'ശ്രദ്ധിക്കുന്നു...',
    'copilot.voiceOutput': 'വായിച്ചു കേൾപ്പിക്കുക',
    'cash.title': 'കൃഷി വരവ് ചെലവ് പുസ്തകം',
    'cash.addIncome': 'വരവ് ചേർക്കുക',
    'cash.addExpense': 'ചെലവ് ചേർക്കുക',
    'cash.income': 'വരവ്',
    'cash.expense': 'ചെലവ്',
    'cash.category': 'വിഭാഗം',
    'cash.amount': 'തുക (₹)',
    'cash.date': 'തീയതി',
    'cash.description': 'കുറിപ്പുകൾ / വിവരണം',
    'cash.net': 'ആകെ സമ്പാദ്യം',
    'cash.breakdown': 'ചെലവുകളുടെ തരംതിരിവ്',
    'cash.insights': 'ധനകാര്യ AI വിശകലനം',
    'cash.empty': 'ലാഭനഷ്ടങ്ങൾ മനസിലാക്കാൻ വരവ് ചെലവുകൾ രേഖപ്പെടുത്തുക.',
    'cash.farmProfitability': 'കൃഷിയിടം തിരിച്ചുള്ള ലാഭവിശകലനം',
    'cash.farmName': 'കൃഷിയിടത്തിന്റെ പേര്',
    'cash.crop': 'വിള',
    'cash.netProfit': 'അറ്റാദായം',
    'cash.unassigned': 'തിരംതിരിക്കാത്തവ',
    'comm.title': 'കർഷക സാമുദായിക ശൃംഖല',
    'comm.feed': 'ചർച്ചാ വേദി',
    'comm.groups': 'കർഷക ഗ്രൂപ്പുകൾ',
    'comm.experts': 'അംഗീകൃത വിദഗ്ദ്ധർ',
    'comm.createPost': 'പുതിയ വിവരങ്ങൾ പങ്കുവെക്കുക അല്ലെങ്കിൽ സംശയങ്ങൾ ചോദിക്കുക...',
    'comm.postBtn': 'പോസ്റ്റ് ചെയ്യുക',
    'comm.nearby': 'അടുത്തുള്ള കർഷകർ',
    'comm.repScore': 'കമ്മ്യൂണിറ്റി റേറ്റിംഗ്',
    'comm.badge': 'ബാഡ്ജ് നിലവാരം',
    'comm.follow': 'പിന്തുടരുക',
    'comm.message': 'സന്ദേശം അയക്കുക'
  }
};

async function run() {
  console.log('Reading LanguageContext.tsx...');
  let content = fs.readFileSync(LANG_CONTEXT_PATH, 'utf8');

  // Insert each populated dictionary into LanguageContext.tsx
  for (const [lang, dict] of Object.entries(dictionaries)) {
    const targetSearch = `  ${lang}: {},`;
    if (content.includes(targetSearch)) {
      console.log(`Inserting translations for language: ${lang}`);
      const items = Object.entries(dict)
        .map(([k, v]) => `    '${k}': '${v.replace(/'/g, "\\'")}'`)
        .join(',\n');
      const replacement = `  ${lang}: {\n${items}\n  },`;
      content = content.replace(targetSearch, replacement);
    } else {
      console.log(`Language ${lang} already populated or block not found.`);
    }
  }

  fs.writeFileSync(LANG_CONTEXT_PATH, content, 'utf8');
  console.log('LanguageContext.tsx successfully updated with Marathi, Tamil, Kannada, Bengali, Punjabi, and Malayalam translations!');
}

run();
